- package.json
> chore(package): update source-map-support to version 0.4.11

- package.json
> chore(package): update electron-builder to version 12.3.1

- package.json
> chore(package): update electron-builder to version 13.3.2

- package.json
> chore(package): update electron-builder to version 13.5.0

- package.json
> chore(package): update spectron to version 3.6.0

- package.json
> chore(package): update electron-builder to version 13.6.0

- package.json
> chore(package): update electron to version 1.4.15

- package.json
> chore(package): update electron-builder to version 13.9.0

- package.json
> chore(package): update electron-builder to version 13.11.1

- package.json
Closes #76
https://greenkeeper.io/
> chore(package): update electron-builder to version 15.1.1

- package.json
> chore(package): update electron to version 1.6.2

- package.json
> chore(package): update electron-builder to version 15.5.1

- package.json
> chore(package): update electron-builder to version 15.6.3

- package.json
> chore(package): update electron-builder to version 16.8.2

- package.json
Closes #85
https://greenkeeper.io/
> chore(package): update electron-builder to version 17.0.3

- src/background.js
> Fixes that mail count is shown in tray bar

- src/background.js
@BeatPlus https://github.com/BeatPlus/Protonmail/issues/51 Isn't working for me in your latest version, I think this PR will fix the issue, at least it works for me (MacOS Sierra 10.12.3)
> added fix from https://github.com/electron/electron/pull/5557

- package.json
> chore(package): update electron-builder to version 17.1.2

- package.json
> chore(package): update electron-dl to version 1.9.0

- src/sidebar.js
> Prefill username after loading is done

- .travis.yml
- package.json
- src/background.js
- src/browser.js
Upon a tag push Travis will build releases for all platforms. Windows is built inside Wine. If a tag is pushed and no release exists at GH, the CI will create a release draft. Completely excellent.
> Ci build releases

- .travis.yml
- e2e/unread-notifications-count.e2e.js
- package.json
- src/auto-updater.js
- src/background.js
- yarn.lock
This can't be merged until MacOS signing cert is implemented in Travis.
> Auto update for MacOS/Win

- .eslintrc.json
- .travis.yml
- package.json
- src/background.js
- src/browser.js
- src/helpers/window.js
- src/menu.js
- src/menu/dev_menu_template.js
- src/menu/edit_menu_template.js
- src/sidebar.js
- src/tray.js
- yarn.lock
husky will add a git hook so eslint--fix will be ran before each commit, it will help us to keep the code cleaner
> add eslint

- package.json
- src/browser.js
- src/menu.js
- src/stylesheets/main.scss
Adds option to toggle sidebar with a shortcut (CtrlShiftH) or through the menu.
I could not add an e2e test as webdriverio does not support multiple keys.
> Add option to toggle sidebar, solves #148

- src/background.js
> issue 146: fix JS error upon second app start

- src/renderer/components/Wrapper/styles.scss
> fix(sidebar): fix hided column width

- package.json
> fix(icon): case sens path to mac icon used by linux

- src/main/index.js
- src/main/index.spec.js
Solves notifications shown in Windows upon new email.
#197
> fix(notifications): fix in Windows

- .circleci/config.yml
> ci(circle): deploy to snap store

- package.json
- scripts/after-pack.js
"The SUID sandbox helper binary was found, but is not configured correctly."
https://github.com/electron/electron/issues/17972
> fix(snap): installation issue
